#!/bin/sh

if [ -d /run/systemd/system ]; then
	if systemctl is-active --quiet phpPHP_VERSION-fpm.service; then
		exec systemctl --kill-who=main --signal=USR1 kill phpPHP_VERSION-fpm.service
	fi
else
	if service phpPHP_VERSION-fpm status >/dev/null 2>&1; then
		exec service phpPHP_VERSION-fpm reopen-logs
	fi
fi
