#!/bin/sh
CONFFILE=/etc/php/PHP_VERSION/fpm/php-fpm.conf
[ -r /etc/default/phpPHP_VERSION-fpm ] && . /etc/default/phpPHP_VERSION-fpm
CONF_PIDFILE=$(sed -n 's/^[[:space:]]*pid[[:space:]]*=[[:space:]]*//p' $CONFFILE)
PIDFILE=${CONF_PIDFILE:-/run/php/phpPHP_VERSION-fpm.pid}
[ -r "$PIDFILE" ] && kill -USR1 $(cat "$PIDFILE") > /dev/null
exit 0
