#!/bin/sh
CONFFILE=/etc/php/8.5/fpm/php-fpm.conf
[ -r /etc/default/php8.5-fpm ] && . /etc/default/php8.5-fpm
CONF_PIDFILE=$(sed -n 's/^[[:space:]]*pid[[:space:]]*=[[:space:]]*//p' $CONFFILE)
PIDFILE=${CONF_PIDFILE:-/run/php/php8.5-fpm.pid}
[ -r "$PIDFILE" ] && kill -USR1 $(cat "$PIDFILE") > /dev/null
exit 0
