#!/bin/bash

sapi=$1
php=PHP_VERSION
install_dir=/usr/local/php/PHP_VERSION
debconf_fix=DEBIAN_FRONTEND=noninteractive
apt_install="sudo $debconf_fix apt-fast -y -o Dpkg::Options::=--force-confdef --no-install-recommends install"

check_installed() {
  sudo dpkg-query --show --showformat='${db:Status-Status}' "$1" 2>/dev/null
}

restart_service() {
  sudo service "$1" restart || sudo service "$1" restart || sudo service "$1" start
}

install_apache2() {
  sudo service nginx stop 2>/dev/null || true
  if ! check_installed apache2; then
    $apt_install apache2-bin apache2 libapache2-mod-fcgid
  else
    if ! [[ "$(apache2 -v 2>/dev/null | grep -Eo "([0-9]+\.[0-9]+)")" =~ 2.[4-9] ]]; then
      sudo "$debconf_fix" apt-get purge apache* apache-* >/dev/null
      $apt_install apache2-bin apache2 libapache2-mod-fcgid
    fi
  fi
  sudo sed -i -e 's/60/5/' -e 's/20/5/' /etc/init.d/apache2
  . /etc/apache2/envvars
  sudo cp "$install_dir"/etc/apache2/conf-available/*.conf /etc/apache2/conf-available/
  sudo cp "$install_dir"/etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/
  echo "ServerName localhost" | sudo tee -a /etc/apache2/apache2.conf >/dev/null 2>&1
}

install_nginx() {
  sudo service apache2 stop 2>/dev/null || true
  if ! check_installed nginx; then
    $apt_install nginx
  fi
  sudo cp "$install_dir"/etc/nginx/sites-available/default /etc/nginx/sites-available/
}

if ! command -v apt-fast >/dev/null; then sudo ln -sf /usr/bin/apt-get /usr/bin/apt-fast; fi

case $sapi in
  apache*:apache*)
    install_apache2
    sudo a2disconf php"$php"-fpm || true
    sudo a2dismod mpm_event proxy_fcgi 2>/dev/null || true
    sudo a2enmod mpm_prefork php"$php"
    restart_service apache2
    ;;
  fpm:apache*)
    install_apache2
    sudo a2dismod php"$php" 2>/dev/null || true
    sudo a2enmod proxy_fcgi
    sudo a2enconf php"$php"-fpm
    restart_service php"$php"-fpm
    restart_service apache2
    ;;
  cgi:apache*)
    install_apache2
    sudo a2dismod php"$php" mpm_event 2>/dev/null || true
    sudo a2enmod mpm_prefork actions cgi
    sudo a2disconf php"$php"-fpm 2>/dev/null || true
    sudo a2enconf php"$php"-cgi
    restart_service apache2
    ;;
  fpm:nginx)
    install_nginx
    restart_service php"$php"-fpm
    sudo service nginx restart
    ;;
  apache*)
    restart_service apache2
    ;;
  fpm)
    restart_service php"$php"-fpm
    ;;
  embed|cgi|phpdbg) ;;
esac

exit 0
